
[theme]
#name = "solarized-dark"
#name = "solarized-light"
#name = "slick"
#name = "modern"
#name = "bad-wolf"
#name = "gruvbox-light"
name = "gruvbox-dark"

[theme.overrides]
separator = "<span font='11'></span>"
#idle_bg = "#123456"
#idle_fg = "#abcdef"

[icons]
name = "awesome"
[icons.overrides]
memory_mem = " RAM "
xrandr = ""
thermometer =" "


[[block]]
block = "xrandr"
#icons = true
resolution = false
#step_width = 5
interval = 600

#[[block]]
#block = "nvidia_gpu"
#label = ""
#show_memory = true
#show_clocks = true
interval = 120

[[block]]
block = "net"
device = "wlan0"
ssid = true
ip = false
bitrate = true
speed_up = true
graph_up = true
interval = 5

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"


[[block]]
block = "disk_space"
path = "/"
alias = ""
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "Σ {average}°"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

[[block]]
block = "uptime"
